sudo: false
language: node_js
env:
  - CXX="g++-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
matrix:
  allow_failures:
  - node_js: "5"
before_install:
  - npm install -g npm@latest-2
node_js:
  - "6"
before_script:
  - npm install -g istanbul gulp mocha
  - npm install coveralls
  - git clone https://github.com/node-red/node-red.git
  - cd node-red
  - npm install
  - export NODE_RED_HOME=`pwd`
  - (cd $NODE_RED_HOME ; npm install nock@~0.48.0)
script:
  - gulp